### ISSUE TITLE
操作没作用

### ISSUE THREAD

**Issue by TxcA** [longforus/KotlinCodeSorter#1]
插件里搜Lifecycle Sorter无意发现还有kotlin的，感谢开发~
**但我这，不管点击菜单，还是快捷键，都没有作用。**

```
Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 19, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
```

**Comment by longforus** [comment]
@TxcA  

我这里是有用的呢  

Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 19, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8


先打开要操作的kotlin类,再点排序  ,点了之后as右下角有报错吗?红色的感叹号,有的话点开看看

**Comment by TxcA** [comment]
@longforus 

[http://cdn.qson.cn/test_as.mp4](http://cdn.qson.cn/test_as.mp4)

你看下我的操作是不是有问题，今天测试了下感觉还是不行。

**Comment by longforus** [comment]
@TxcA 
看你这个代码的顺序就是排序后的顺序啊 ,
默认的顺序是 
字段
init块
第二构造
方法
内部类,
你把那个adapter放到一些方法之间去再试试呢?

**Comment by TxcA** [comment]
嘿嘿，我还以为可以排生命周期。其它的我写的时候基本都习惯这样写了，所以没看出变化。

**Comment by longforus** [comment]
@TxcA 
我这个是排字段方法次序,没做生命周期呢
