### ISSUE TITLE
Support Android Studio 4.1

### ISSUE THREAD

**Issue by kanamares** [longforus/KotlinCodeSorter#4]
Plugin does not work on Android Studio 4.1

**Comment by longforus** [comment]
@kanamares What is the version of the plugin? the new version in here : [https://github.com/longforus/KotlinCodeSorter/releases/tag/v1.2.2](https://github.com/longforus/KotlinCodeSorter/releases/tag/v1.2.2)
Because it is getting approval by jetbrins right now,So you have to update it manually.

**Comment by kanamares** [comment]
v.1.2.1 in Marketplace

**Comment by longforus** [comment]
@kanamares first you need uninstall old version.
second download the new version v1.2.2 ,install by manually.

**Comment by kanamares** [comment]
done! thx!
